//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppConfig
    {
        public int AppConfigId { get; set; }
        public string Appkey { get; set; }
        public string AppValue { get; set; }
        public string Remarks { get; set; }
    }
}
