//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateJobMst
    {
        public int CandidateJobId { get; set; }
        public Nullable<int> RegistrationId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsCertificateIssued { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string FileName { get; set; }
        public string OfferLetter { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string IpAddress { get; set; }
    
        public virtual CompnayMst CompnayMst { get; set; }
        public virtual RegistrationMst RegistrationMst { get; set; }
    }
}
