//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skill.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CandidateLanguage
    {
        public int CadidateLanguageId { get; set; }
        [Required]
        public Nullable<int> RegistrationId { get; set; }
        [Required]
        public Nullable<int> LanguageMstId { get; set; }
    
        public virtual LanguageMst LanguageMst { get; set; }
    }
}
