//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skill.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CourseMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseMst()
        {
            this.CandidateAttendances = new HashSet<CandidateAttendance>();
            this.CourseDocMappings = new HashSet<CourseDocMapping>();
            this.CourseRegistrationDetails = new HashSet<CourseRegistrationDetail>();
        }
    
        public int CourseId { get; set; }
        [Required]
        [Display(Name ="Category")]
        public int CategoryId { get; set; }
        [Required]
        [Display(Name = "Trainer")]
        public Nullable<int> TrainerId { get; set; }
        [Required]
        [Display(Name = "Branch")]
        public Nullable<int> BranchId { get; set; }
        [Required]
        [Display(Name = "Course Name")]
        public string CourseName { get; set; }
        [Required]
        [Display(Name = "Course Abb")]
        public string CourseAbb { get; set; }
        [Required]
        [Display(Name = "Shot Description")]
        public string ShotDescription { get; set; }
        public string Overview { get; set; }
        public string Description { get; set; }
        [Display(Name = "Offline Seat")]
        public Nullable<int> OfflineSeat { get; set; }
        [Display(Name = "Online Seat")]
        public Nullable<int> OnlineSeat { get; set; }

        [Display(Name = "Start Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> StartDate { get; set; }

        [Display(Name = "End Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> EndDate { get; set; }

        [Display(Name = "Duration In Hours")]
        public Nullable<double> DurationInHours { get; set; }

        [Display(Name = "Extention Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> ExtentionDate { get; set; }

        [Display(Name = "Pending Online Seat")]
        public Nullable<int> PendingOnlineSeat { get; set; }
        [Display(Name = "Pending Offline Seat")]
        public Nullable<int> PendingOfflineSeat { get; set; }
        [Display(Name = "Avg Rating")]
        public Nullable<double> AvgRating { get; set; }
        [Display(Name = "Course PDF")]
        public string CoursePDF { get; set; }
        [Display(Name = "Course Photo")]
        public string CoursePhoto { get; set; }

        [Display(Name = "Course Video YouTube Link")]
        [Url]
        public string CourseVideoYouTubeLink { get; set; }
        [Display(Name = "Course Doc")]
        public Nullable<int> CourseDocId { get; set; }
        [Display(Name = "Course Fee")]
        public Nullable<decimal> CourseFee { get; set; }
        [Display(Name = "Course Initial Fee")]
        public Nullable<decimal> CourseInitialFee { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string IpAddress { get; set; }
    
        public virtual BranchMst BranchMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateAttendance> CandidateAttendances { get; set; }
        public virtual CategoryMst CategoryMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseDocMapping> CourseDocMappings { get; set; }
        public virtual TrainerMst TrainerMst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseRegistrationDetail> CourseRegistrationDetails { get; set; }
    }
}
