//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuMst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menuMst()
        {
            this.roleMenuMappings = new HashSet<roleMenuMapping>();
        }
    
        public int MenuID { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public Nullable<int> MenuType { get; set; }
        public bool IsAdminPage { get; set; }
        public string Name { get; set; }
        public string NameGuj { get; set; }
        public string URL { get; set; }
        public bool ShowInMenu { get; set; }
        public string Icon { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string HostName { get; set; }
        public string IpAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roleMenuMapping> roleMenuMappings { get; set; }
    }
}
