//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace skill.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class skillEntities : DbContext
    {
        public skillEntities()
            : base("name=skillEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppConfig> AppConfigs { get; set; }
        public virtual DbSet<BranchMst> BranchMsts { get; set; }
        public virtual DbSet<CandidateAttendance> CandidateAttendances { get; set; }
        public virtual DbSet<CandidateDoc> CandidateDocs { get; set; }
        public virtual DbSet<CandidateJobMst> CandidateJobMsts { get; set; }
        public virtual DbSet<CandidateLanguage> CandidateLanguages { get; set; }
        public virtual DbSet<CategoryMst> CategoryMsts { get; set; }
        public virtual DbSet<CityMst> CityMsts { get; set; }
        public virtual DbSet<CompnayMst> CompnayMsts { get; set; }
        public virtual DbSet<Contactu> Contactus { get; set; }
        public virtual DbSet<CourseDocMapping> CourseDocMappings { get; set; }
        public virtual DbSet<CourseMst> CourseMsts { get; set; }
        public virtual DbSet<CoursePaymentDetail> CoursePaymentDetails { get; set; }
        public virtual DbSet<CourseRegistrationDetail> CourseRegistrationDetails { get; set; }
        public virtual DbSet<DistrictMst> DistrictMsts { get; set; }
        public virtual DbSet<DocumentMst> DocumentMsts { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<LanguageMst> LanguageMsts { get; set; }
        public virtual DbSet<menuMst> menuMsts { get; set; }
        public virtual DbSet<RegistrationMst> RegistrationMsts { get; set; }
        public virtual DbSet<roleMenuMapping> roleMenuMappings { get; set; }
        public virtual DbSet<roleMst> roleMsts { get; set; }
        public virtual DbSet<SiteConfig> SiteConfigs { get; set; }
        public virtual DbSet<StateMst> StateMsts { get; set; }
        public virtual DbSet<templateMst> templateMsts { get; set; }
        public virtual DbSet<TrainerMst> TrainerMsts { get; set; }
        public virtual DbSet<UserMst> UserMsts { get; set; }
        public virtual DbSet<userRole> userRoles { get; set; }
    }
}
